import Head from "next/head";
import Hero from "../components/Hero";
import AboutMe from "../components/AboutMe";
import Skills from "../components/Skills";
import Animated from "../components/Animated";
import AditionalInfo from "../components/AditionalInfo";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <AditionalInfo />
      <Skills />
      <AboutMe />
      <Animated />
    </div>
  );
}
